"""update user table

Revision ID: 1f7a2b5015ba
Revises: 1706d20edc33
Create Date: 2024-12-05 22:44:55.911042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7a2b5015ba'
down_revision: Union[str, None] = '1706d20edc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 'role',
        server_default= 'user',
        existing_type=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 'role',
        server_default=None
    )
    # ### end Alembic commands ###
