"""updating borrow table

Revision ID: 94318a5e8890
Revises: 232a65756b4a
Create Date: 2024-12-08 01:46:32.368528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94318a5e8890'
down_revision: Union[str, None] = '232a65756b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_history', sa.Column('status', sa.String, nullable=False, server_default= "borrowed"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_history', 'status')
    # ### end Alembic commands ###
